version: "3.1"

services:
  db:
    image: postgres:latest
    ports:
      - "127.0.0.1:5436:5432"
    volumes:
      - ${PWD}/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: pg
    restart: always
