[package]
name = "pqb_cli"
version = "0.1.5"
authors = ["Konstantin <phpconf@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
clap = "2.33.3"
